### ISSUE TITLE
Real Time Data

### ISSUE THREAD

**Issue by GeorgAI** [amacado/handelsregister-cli#5]
How regularly will the data from the Handelsregister be updated? 

For example, the list of shareholders could change at any time.

Thank you for the effort you are putting into this open source project!

**Comment by amacado** [comment]
Hi @GeorgAI, i'm not sure if I understand your question. When executing, the CLI will always fetch the latest public available data at [handelsregister.de](https://www.handelsregister.de/). I'm not responsible or in any terms related to the actual service of handelsregister.de and I'm unable to tell you how frequent the data will be updated on their side. Did that answer your question?

**Comment by GeorgAI** [comment]
Hi @amacado, I understand. So the data is always directly fetched from handelsregister.de and not prescrawled. 

Thank you for the answer!

**Comment by amacado** [comment]
@GeorgAI correct, this CLI is basically just an automated click-through the advanced search form on handelsregister.de.
